### ISSUE TITLE
Log folders reset

### ISSUE THREAD

**Issue by user00800** [grayfallstown/Chia-Plot-Status#106]
If the log folders are located on a network drive and it turns off (for example, the PC reboots), then they are deleted and they have to be added again. Is it possible to prevent them from being deleted? Thanks

**Comment by grayfallstown** [comment]
Well, what happens is that ChiaPlotStatus will check if each log folder in its config exists.
If a folder does not exist, it does not add it.
So apparently the problem is that `Directory.Exists(path)` does return false. Which makes sense while the remote filesystem is not available.

I will remove the check. It just does not make sense in the context of network shares.

Give me a few minutes to build a new Release.

**Comment by grayfallstown** [comment]
Try 0.11.9
