### ISSUE TITLE
time in harverster statistics

### ISSUE THREAD

**Issue by josemanuelhda** [grayfallstown/Chia-Plot-Status#108]
sorry to point this as an issue, it is simply a question, what is the period of time used por harverster stats? I see number of proofs found, but I don't know how much time it took to get them

same as the rest of statistics, I love harverster stats by the way, thanks for adding them

**Comment by grayfallstown** [comment]
Hi,
the harvester dialog uses the last 500 entries. It calculates the time, but I forgot to add this to the gui. I will change this, but I am currently busy on a different Project.

The statistics dialog shows the plotting statistics over all the found log files. So the time is dependent on your oldest log. If it would only show the last n days, you could not compare how your plotting improved over time with different strategies.

**Comment by josemanuelhda** [comment]
thanks for the info, so if I have understood, if I get in harverster 10 challenges per minute in the results, it would mean that the whole stats for harvester are for a 50 minutes period (500 lines with 10 challenges per minute)

**Comment by grayfallstown** [comment]
Yes.

I plan to replace the GUI with an electron based dashboard at some time in the future, so I can add proper charts/graphs that can be interfaced with. This would allow me to fix a few bugs that are caused by unexpected behavior in the underlying GUI library, like not being able to reorder columns via drag and drop or losing the current position in a table when the table date gets refreshed. This should allow me to be way more flexible on how I present information and things should get a lot easier to understand. This one is on me, tho. I forgot to add this information to the GUI.

The thing is, my focus is currently on another project. A faucet for all the chia forks that I plan to bring live on Friday: https://penny-faucets-for-chia-forks.net/

Once the faucet runs properly, I will come back to the Chia-Plot-Status GUI Rewrite and things should get more clearly presented.

**Comment by josemanuelhda** [comment]
great. everything clear now, I close the issue and wish you success with your new and old developmnts :)
