### ISSUE TITLE
Calculate ETA and Remaining Time for first plot logs too

### ISSUE THREAD

**Issue by whitetechnologies** [grayfallstown/Chia-Plot-Status#23]
If using CLI, a log is not automatically generated. Therefore, for CLI users, it is necessary to use something like "tee" (a CLI output tool) to create a log

The command to do so would be:  .\chia.exe plots create -k 32 -n 2 -u 128 -t G:\ChiaTemp -d O:\Chia8O -r 2 -n 5 | tee -filepath C:\Users\<>\.chia\mainnet\plotter\plots-5-6-2021-B.txt

However, the log created by this is slightly different than the one created by the GUI. It does not have the same header, but it does have all the same information (attached example). 

It seems that Chia Plot Status is not able to correctly parse a manually generated log. It picks up some of the info, but is missing critical parts like: ETA, Time Remaining etc 

It would be extremely helpful (and hopefully easy to tweak) to be able to read this type of log in addition to the GUI. 

[plots-5-6-2021-A.txt](https://github.com/grayfallstown/Chia-Plot-Status/files/6437517/plots-5-6-2021-A.txt)

**Comment by grayfallstown** [comment]
I create almosts all my logs using tee and only a few via the gui for testing.

When I put your log file in an otherwise empty folder and have no other plot log folder in my selection I get the result you describe.

I think there is a little misunderstanding here. Chia Plot Status needs at least one finished plot log (as in total time is printed in the log) to calculate ETA and is getting better in predicting with each finished plot log you have, as it learns about how fast plotting on your system is on the various drives is.

I thrown in one of my finished plot logs in the folder with your file:

[535f100e-636b-431f-8e3e-a0898ee25e3d.log](https://github.com/grayfallstown/Chia-Plot-Status/files/6439338/535f100e-636b-431f-8e3e-a0898ee25e3d.log)

![Screenshot](https://user-images.githubusercontent.com/50076933/117404671-a18f7800-af0a-11eb-9781-96f80af03c58.JPG)

And ETA gets calculated based on the finished one.

I could use all my existing plot logs to build an average across all my drives and use that as the default in the program. That would show an ETA and Time Remaining even if the user has no finished plots. The ETA and Warning/Error Thresholds would be imprecise for systems unlike mine, but then the user would see something and the current Thresholds are diced anyway.

**Comment by grayfallstown** [comment]
The new Release calculates ETA and Time Remaining even if you do not have finished plot logs

**Comment by whitetechnologies** [comment]
thank you for looking into this. Yes I can see now that it is indeed parsing and calculating correctly. Thank you for an excellent tool!
