### ISSUE TITLE
add ability to select and delete logfiles from the app 

### ISSUE THREAD

**Issue by magnusmyklebost** [grayfallstown/Chia-Plot-Status#39]
i have a lot of possible dead plots, which i know is dead, and a series of plots that come up as "slow  48 / 18m" even though they are deleted along with the temp files. 
deleting these log files are time consuming, since you can only open the file from the app and not "show in explorer " etc.

suggestion:
-add the ability to select plots from the list and then delete these files
-add the ability to select all possible dead, confirmed dead and slow plots and then delete these
-add the ability to show file in folder, so you could delete it in windows explorer

thanks

**Comment by grayfallstown** [comment]
When you create plots with chia plot create --num 20 you get multiple processes in the same logfile. Deleting the file of the last failed would delete the 19 previously finished plot logs as well, drastically reducing the quality of ETA/Time Remaining as well as warning and error thresholds.

That is one reason why I don't want Chia Plot Status to delete files. I could implement it so that you can confirm the death of all the selected processes. Then you can hide them.
I will make the filter selection persist between application starts.

**Comment by grayfallstown** [comment]
In the current release
