### ISSUE TITLE
Enhancement: Ability to not lock the log files while chiastatus is running?

### ISSUE THREAD

**Issue by revlisoft** [grayfallstown/Chia-Plot-Status#57]
Would it be possible to not lock the log files so I don't have to shut down chia status (possibly from multiple machines) to delete/clear any logs?

**Comment by grayfallstown** [comment]
Already possible, but will not become the default behaviour as it has drawbacks. See [#40](https://github.com/grayfallstown/Chia-Plot-Status/issues/40#issuecomment-841025993)

Please don't delete finished logs. Chia Plot Status uses them to calculate ETA and warning thresholds.

**Comment by revlisoft** [comment]
That's perfect.  I'm keeping the successful runs in the log directories but sometimes there are failed runs that I want to clear out as it skews the ETA/warnings

**Comment by grayfallstown** [comment]
Like when you test plotting with too much parallelism for your drive? Can you elaborate?

What should happen is that only finished plots are used to calculate these. Chia Plot Status tries to take only finished plots that fit your current configuration as in buffer size or temp drives.

**Comment by revlisoft** [comment]
I have 3 different machines running and each one has anywhere from 2-4 temp drives and 7-8 target drives.  I'm using https://github.com/swar/Swar-Chia-Plot-Manager to manage all the plots being created.  Sometimes I have to restart the entire manager or there is a process or 2 that failed due to various issues so after fixing it I wanted to clear out the invalid log files.  Maybe a nice feature in the chia-plot-status would to allow us to delete log files directly so we can keep it clean with only valid logs?

**Comment by grayfallstown** [comment]
One of the problems is that if you use --num 20 to plot 20 plots in a row they all end up in the same logfile. Deleting the file because the last one failed deletes 19 finished plots that are needed for ETA/Warning calculation.

Another Problem is that people use various methods to collect their logs from multiple plotting rigs. Very often using scp or rsync in a cron job. That would bring the deleted files right back (copied from plotting rig again) and the user might not understand why after he clicked delete in Chia Plot Status.

The mark as dead feature works around those problems (click on health status). The problem is, you have to confirm each dead plot individually for now (this will be changed).

**Comment by revlisoft** [comment]
oic I don't believe I have that issue since it looks like swar's plot manager creates a brand new log file for each plot so it doesn't reuse it.  Good to keep that in mind though.  Great app BTW!


![Screenshot 2021-05-20 115229](https://user-images.githubusercontent.com/4432112/119010312-eb904900-b961-11eb-85f0-c4a39f90d041.jpg)
