### ISSUE TITLE
Enhancement: Build setup.exe to include version

### ISSUE THREAD

**Issue by revlisoft** [grayfallstown/Chia-Plot-Status#71]
Minor issue but it would be nice if the setup file was the name of the project with a release number. Like chia-plot-status-0.10.1-setup.exe

**Comment by grayfallstown** [comment]
In that case I had to update the download links in the readme and on the website for each release.
Used to do that, was not fun. Could be scripted, but moving the readme into templates brings its own set of problems especially regarding pull requests

**Comment by revlisoft** [comment]
Oic. I guess if the update process was more seamless this would be not as important. :)

**Comment by grayfallstown** [comment]
Name of the project can be done easily.
The Problem is the update link to Setup.exe is hardcoded into the application as it was meant to stay that way forever.
Renaming the Setup would mean I need to have the Setup twice in the next few releases. Once with the old name, once with the new one or older versions could no longer update.

**Comment by revlisoft** [comment]
Got it. Not worth the effort and headache.
