### ISSUE TITLE
Dependency problems prevent configuration of chiaplotstatus

### ISSUE THREAD

**Issue by cyperbg** [grayfallstown/Chia-Plot-Status#87]
Installing the deb file via the GUI throws the same error.
If I do it in the terminal I get this:

```
sudo dpkg -i ChiaPlotStatus.linux-x64.deb
[sudo] password for xxxxxx: 
Selecting previously unselected package chiaplotstatus.
(Reading database ... 217962 files and directories currently installed.)
Preparing to unpack ChiaPlotStatus.linux-x64.deb ...
Unpacking chiaplotstatus (0.10.3) ...
dpkg: dependency problems prevent configuration of chiaplotstatus:
 chiaplotstatus depends on libicu66 | libicu65 | libicu64 | libicu63 | libicu62 | libicu61 | libicu60 | libicu59 | libicu58 | libicu57 | libicu56 | libicu55 | libicu54 | libicu53 | libicu52; however:
  Package libicu66 is not installed.
  Package libicu65 is not installed.
  Package libicu64 is not installed.
  Package libicu63 is not installed.
  Package libicu62 is not installed.
  Package libicu61 is not installed.
  Package libicu60 is not installed.
  Package libicu59 is not installed.
  Package libicu58 is not installed.
  Package libicu57 is not installed.
  Package libicu56 is not installed.
  Package libicu55 is not installed.
  Package libicu54 is not installed.
  Package libicu53 is not installed.
  Package libicu52 is not installed.

dpkg: error processing package chiaplotstatus (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.24-1ubuntu4) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Errors were encountered while processing:
chiaplotstatus
```

**Comment by grayfallstown** [comment]
Which Linux and which version? Guessing ubuntu 21.04.

https://askubuntu.com/a/80794

sudo dpkg  - - force-all -i ChiaPlotStatus.linux-x64.deb should ignore the deps and just install anyway but I did not test it. 

It is safer to look in the Readme under build it yourself.

**Comment by cyperbg** [comment]
I have 2 machines with Ubuntu - 20.10 and 21.04 and the same thing happens on both.
The weird thing is that even after getting this error message it still appears in the program menu and I can open it. But after a restart it disappears.

**Comment by grayfallstown** [comment]
> it still appears in the program menu and I can open it. But after a restart it disappears.

Thats.. weird. This is the first time I heard about such a thing.. And I used linux and ubuntu specifically 8 years straight at work. That disappearing part I mean.

That it does run does not wonder me at all. Every modern ubuntu should have almost all the required deps installed anyway.

The thing is my private rig runs windows for gaming and other reasons and there are simply no good tools to build deb packages on windows I know of and I do not like WSL and have no free ram left for a VM. Otherwise this should be an easy fix.

You could open/unpack the deb in an archive manager and move the files there they belong (the paths in the deb file are correct, just move them to the same folders on your machine) 7zip would work, the default ubuntu archive manager might as well.

**Comment by grayfallstown** [comment]
I just cloned [dotnet-packaging](https://github.com/qmfrederik/dotnet-packaging), the tool I use to build the deb package. Maybe the easiest way is just to change the generator code so it works for ubuntu > 20.04

**Comment by grayfallstown** [comment]
I created a version with more lenient dependencies: https://github.com/grayfallstown/Chia-Plot-Status/releases/download/ubuntu-deps-test/ChiaPlotStatus.linux-x64.deb

Mind testing?

**Comment by cyperbg** [comment]
That version installed fine just by opening the deb file. Thank you so much.

Btw of all the programs related to Chia yours is the one I like the most. Very useful.
