### ISSUE TITLE
TROJAN FOUND

### ISSUE THREAD

**Issue by OzboiMr** [grayfallstown/Chia-Plot-Status#92]
Windows Security FOUND TROJAN!

**Comment by grayfallstown** [comment]
Please take a look at issue #91

The problem is known, currently in the working, 2 of 3 flagged files were already deemed save by microsoft malware analysts and are no longer flagged. The third file is still being analysed. This all happened once already and it will likely turned out as false positive like it did [last time](https://github.com/grayfallstown/Chia-Plot-Status/issues/2#issuecomment-843279417)

There is also [a note explaining all this in the download section](https://github.com/grayfallstown/Chia-Plot-Status#installation--download).

**Comment by grayfallstown** [comment]
Closing this as duplicate
